# A human-readable name of the Recipe for listing in UIs.
name: 'Test JAR'
description: "Recipe for setting up JSON:API Reference for testing"
# The type key is similar to the package key in module.info.yml. It
# can be used by the UI to group Drupal recipes. Additionally,
# the type 'Site' means that the Drupal recipe will be listed in
# the installer.
type: 'Testing'

install:
  # An array of modules or themes to install, if they are not already.
  # The system will detect if it is a theme or a module. During the
  # install only simple configuration from the new modules is created.
  # This allows the Drupal recipe control over the configuration.
  - jsonapi
  - jsonapi_reference
  - devel_generate
  - navigation
